In [ ]:
print("hello world!")

hello world!


In [ ]:
height = 6
length = 3
width = 2
volume = height * length * width
print(volume)

36


In [ ]:
rent = 1700
print(rent)
rent =2000
rent = rent + 700
print(rent)

1700
2700


In [ ]:
print('hello' + 'world')
print("hello" + "" + "world")

helloworld
helloworld


In [ ]:
word = "hello"
print(word *5)

hellohellohellohellohello


In [ ]:
word_length= len('shape AI')
print(word_length)

8


In [ ]:
decimal = float (3)
print(decimal)

3.0


In [ ]:
marks = 15
subject = 'coding'
semester = 'first'
print(subject + str(marks))
result = "i was able to score" + str(marks)  + "in" + "my" + (semester) + "semester"
print(result)

coding15
i was able to score15inmyfirstsemester


In [ ]:
print("EG:1")
print("mohammed has{} baloons".format(27))

print("ERG:2")
animal = "dog"
action = "bite"
print("does your {} {}".format(animal,action))
print("EG:3")
maria_string = "maria loves {} and {}"
print(maria_string.format("maths", "statistics"))

EG:1
mohammed has27 baloons
ERG:2
does your dog bite
EG:3
maria loves maths and statistics


In [ ]:
students = ['pam',  'sam', 'austin',  'banner', 'rocky', 'steve' ]
print(students)

['pam', 'sam', 'austin', 'banner', 'rocky', 'steve']


In [ ]:
print(students[0])
print(students[1])
print(students[2])


pam
sam
austin


In [ ]:
print(students[-1])
print(students[-2])
print(students[-3])

steve
rocky
banner


In [ ]:
students = ['pam',  'sam', 'austin',  'banner', 'rocky', 'steve','clark', 'diana','tony' ]
student = "berry"
marvel = students[4:7]
flash = student[:3]
print(marvel)
print(flash)


['rocky', 'steve', 'clark']
ber


In [ ]:
print(len(students))
print(len(student))

9
5


In [ ]:
sep_str = "\n".join(["jack", "o", "lantern"])
print(sep_str)

jack
o
lantern


In [ ]:
import time
import numpy as np

In [ ]:
x = np.random.rand(1000000000)


In [ ]:
start = time.time()
mean = sum (x)/ len (x)
print(time.time() - start)

91.81222558021545


In [ ]:
start = time.time()
mean_np = np.mean(x)
print(time.time() - start)

1.1883327960968018


In [ ]:
x = np.array([1,2,3,4,5,])
print('x = ', x)

x =  [1 2 3 4 5]


In [ ]:
x = np.array([1,2,3,4,5,])
print()
print('x = ', x)
print()

print('x has dimension: ', x.shape)
print('x is an object of type:', type(x))
print('the elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

x has dimension:  (5,)
x is an object of type: <class 'numpy.ndarray'>
the elements in x are of type: int64


In [ ]:
x = np.array("hello world")
print()
print('x = ', x)
print()
print('x has dimension: ', x.shape)
print('x is an object of type:', type(x))
print('the elements in x are of type:', x.dtype)





x =  hello world

x has dimension:  ()
x is an object of type: <class 'numpy.ndarray'>
the elements in x are of type: <U11


In [ ]:
x = np.array([1,2 , "world"])
print()
print('x = ', x)
print()
print('x has dimension: ', x.shape)
print('x is an object of type:', type(x))
print('the elements in x are of type:', x.dtype)


x =  ['1' '2' 'world']

x has dimension:  (3,)
x is an object of type: <class 'numpy.ndarray'>
the elements in x are of type: <U21


In [ ]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print()
print('y =\n ', y)
print()
print('y has dimension: ', x.shape)
print('y is an object of type:', type(y))
print('the elements in y are of type:', y.dtype)


y =
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

y has dimension:  (3,)
y is an object of type: <class 'numpy.ndarray'>
the elements in y are of type: int64


In [ ]:
x = np.arange(20).reshape(4,5)
print()
print('original x = ', x)
print()


original x =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [ ]:
x = np.array([1,2,3,4,5])
print()
print('x = ', x)
print()


x =  [1 2 3 4 5]



In [ ]:
x = np.array([1,2,3,4,5])
print()
print('original:\n x = ', x)
print()
x[3]=20
print('modified:\n x = ', x)


original:
 x =  [1 2 3 4 5]

modified:
 x =  [ 1  2  3 20  5]


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print()
print('x = \n ', x)
print()


x = 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [ ]:
x = np.array([1,2,3,4,5])
print()
print('original:\n x = ', x)

x  = np.delete(x , [0,4])
print()
print('modified:\n x = ', x)



original:
 x =  [1 2 3 4 5]

modified:
 x =  [2 3 4]


In [ ]:
x = np.array([1,2,3,4,5])
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print('original:\n x = ', x)

x  = np.append(x,  [6])
print()
print('x =  ', x)
x  = np.append(x,  [7,8])
print()
print('x = ', x)

print()
print('original:\n y = ', y)
v  = np.append(y, [[10,11,12]], axis = 0)

print()
print('v = ', y)




original:
 x =  [[1 2 3]
 [4 5 6]
 [7 8 9]]

x =   [1 2 3 4 5 6 7 8 9 6]

x =  [1 2 3 4 5 6 7 8 9 6 7 8]

original:
 y =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

v =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
x = np.array([1,2,3,4,5])
print()
print('original:\n x = ', x)


x = np.insert(x, 2,[-3,-4])
print()
print('modified:\n x = ', x)




original:
 x =  [1 2 3 4 5]

modified:
 x =  [ 1  2 -3 -4  3  4  5]
